name: deploy-react

on:
  workflow_run:
    workflows: ["build-react"] # build-react.yaml の 'name' と一致させる
    types:
      - completed
    branches:
      - main # main ブランチでのビルド完了時のみ実行

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4 # v4 に更新
        with:
          name: build-output
          path: ./build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # このアクションは通常v1で問題ありません
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3 using AWS CLI # s3-sync アクションの代わりにAWS CLIを使用
        run: |
          aws s3 sync ./build s3://${{ secrets.S3_BUCKET_NAME }} --delete
          # CloudFront を使用している場合、以下の行のコメントを解除してキャッシュをクリアできます
          # aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
